format_version: 10
pipelines:
  jenkins_jobs:
    group: Tools
    materials:
      git-da613e5:
        git: https://github.com/srikanth-123git/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:Auv+4f/s/kPyUSeLxgsPNg==:wTsKB2yc8OEgLcUq3+stTraBu6+7lI8HQGT2IqGLPMY=
    stages:
      - Ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: /home/gocd/.local/bin/ansible-playbook, arguments: [ "-i", "jenkins-internal.psrikanth.online,", "tools.yml", "-e", "tool_name=jenkins", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321", "-e", "jenkins_jobs=true" ], run_if: passed}
